query getDockerfileByCommitHash($hashWithFilename: String!) {
  repository(owner: "mongodb", name: "docs-worker-pool") {
    dockerfile: object(
      expression: $hashWithFilename
    ) {
      ... on Blob {
        text
      }
    }
  }
}