query getLastTwoReleaseHashes {
  repository(owner: "mongodb", name: "docs-worker-pool") {
    releases(first: 2, after: null)  {
      nodes {
        tag {
          id
        }
      }
    }
  }
}
