name: Upload Lighthouse reports to Atlas
description: >
  This action reads, averages, and combines 3 Lighthouse runs and uploads the combined scores to MongoDB Atlas
author: 'MongoDB'
runs:
  using: node20
  main: ../dist/upload-lighthouse/index.js
